spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restdb?useUnicode=true&characterEncoding=utf8
    username: ying
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
